// <auto-generated />
using Eroski.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eroski.Migrations
{
    [DbContext(typeof(EroskiContext))]
    partial class EroskiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Eroski.Models.EroskiItems", b =>
                {
                    b.Property<string>("Seccion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("numeroTicket")
                        .HasColumnType("int");

                    b.HasKey("Seccion");

                    b.ToTable("EroskiItems");
                });
#pragma warning restore 612, 618
        }
    }
}
